networks:
  pss-survey_default:
    external: yes
    name: "pss-survey_default"

services:

  dhis_pss_international:
    container_name: "dhis_pss_international"
    entrypoint:
      - "java"
      - "-jar"
      - "target/InternationalInstance.jar"
    environment:
      - "PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/usr/local/openjdk-11"
      - "LANG=C.UTF-8"
      - "JAVA_VERSION=11.0.16"
    hostname: "8d0dd2016366"
    image: "intellisoftdev/dhis_pss_international:v3"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    ports:
      - "7009:7009/tcp"
    working_dir: "/international_javabackend"

  survey:
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
    container_name: "survey"
    entrypoint:
      - "/docker-entrypoint.sh"
    environment:
      - "REACT_APP_API_URL=http://172.104.91.99:7001"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NGINX_VERSION=1.25.1"
      - "PKG_RELEASE=1"
      - "NJS_VERSION=0.7.12"
    hostname: "f643be53180b"
    image: "pss-survey-survey"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "6aaf4eb59f740780c793a74b199fd59ec6a071ce00537a16698c4fb937df13e9"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:7321ea53ffa66f31f9d15d0949a5ece803f5aa0ad7d2572b027fd73b70196764"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "pss-survey"
      com.docker.compose.project.config_files: "/opt/PSS-survey/docker-compose.yml"
      com.docker.compose.project.working_dir: "/opt/PSS-survey"
      com.docker.compose.replace: "d4f695fbdd841ef850c5e82707038920b09d43ed3ce825acd2ae8b7b3eeca3dc"
      com.docker.compose.service: "survey"
      com.docker.compose.version: "2.16.0"
      maintainer: "NGINX Docker Maintainers <docker-maint@nginx.com>"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "pss-survey_default"
    ports:
      - "3001:3001/tcp"
    restart: "unless-stopped"

version: "3.6"