# Use the base image from Docker Hub for the PSS Data Synchronization (latest version)
FROM intellisoftdev/pss_data_sync:latest

# Set required environment variables (if any)

# Expose port 8000 for the PSS Data Synchronization
EXPOSE 8000

# Set the entrypoint and command for the container to start the PSS Data Synchronization
ENTRYPOINT ["cron", "-f"]