services:

  dhis_pss_national:
    container_name: "dhis_pss_national"
    entrypoint:
      - "java"
      - "-jar"
      - "target/PssNationalInstance.jar"
    environment:
      - "PATH=/usr/local/openjdk-11/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/usr/local/openjdk-11"
      - "LANG=C.UTF-8"
      - "JAVA_VERSION=11.0.16"
    hostname: "7c68adf1687f"
    image: "intellisoftdev/dhis_pss_national:v1"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:02"
    network_mode: "bridge"
    ports:
      - "7001:7001/tcp"
    working_dir: "/national_javabackend"

  pss_data_synchronization:
    command:
      - "cron"
      - "-f"
    container_name: "pss_data_synchronization"
    environment:
      - "SOURCE_USERNAME=admin"
      - "SOURCE_PASSWORD=district"
      - "SOURCE_URL=https://pssnational.intellisoftkenya.com/api/events"
      - "TARGET_USERNAME=admin"
      - "TARGET_PASSWORD=district"
      - "TARGET_URL=https://pssinternational.intellisoftkenya.com/api/events"
      - "SOURCE_DATA_ELEMENTS_URL=https://pssnational.intellisoftkenya.com/api/dataElements"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_VERSION=3.9.17"
      - "PYTHON_PIP_VERSION=23.0.1"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207"
    hostname: "c5c3f3f32ea9"
    image: "intellisoftdev/pss_data_sync:latest"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    mac_address: "02:42:ac:11:00:03"
    network_mode: "bridge"
    ports:
      - "8000:8000/tcp"
    working_dir: "/app"

version: "3.6"