# Use the base image specified in the Docker Compose file
FROM intellisoftdev/pss_data_sync:latest

RUN apt-get update && apt-get install -y cron

# Set environment variables
ENV SOURCE_USERNAME=admin
ENV SOURCE_PASSWORD=district
ENV SOURCE_URL=https://pssnational.intellisoftkenya.com/api/events
ENV TARGET_USERNAME=admin
ENV TARGET_PASSWORD=district
ENV TARGET_URL=https://pssinternational.intellisoftkenya.com/api/events
ENV SOURCE_DATA_ELEMENTS_URL=https://pssnational.intellisoftkenya.com/api/dataElements
ENV PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LANG=C.UTF-8
ENV GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
ENV PYTHON_VERSION=3.9.17
ENV PYTHON_PIP_VERSION=23.0.1
ENV PYTHON_SETUPTOOLS_VERSION=58.1.0
ENV PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py
ENV PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207

# Create a directory for the app
WORKDIR /app

# Copy the app source code to the container
COPY . /app

# Install any dependencies required for the app
RUN pip install -r requirements.txt

# Run the command to start the app
CMD ["cron", "-f"]
